<a href="https://colab.research.google.com/github/ThoaaPhann/AI_31_03_2023/blob/main/Housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## ----------------- Housing -----------------

In [ ]:
import pandas as pd
import numpy as np 
from sklearn import datasets 
from sklearn.linear_model import Perceptron 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
url = '/content/Housing.csv'

Housing = pd.read_csv(url)
print(Housing.head())

      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  


In [ ]:
Housing.replace({'yes': 1, 'no': 0, 'furnished': 1, 'unfurnished': 0, 'semi-furnished': 2}, inplace=True)
X = Housing.drop('price', axis=1).values
print(X[:15])

y = Housing['price'].values
print(y[:15])

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
sc = StandardScaler()
sc.fit(x_test)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

model = Perceptron(max_iter = 1000000, eta0= 0.01, random_state = 0) #so lan train, toc do hoc
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)

print(y_pred[:15])
print(y_test[:15].T)
print("Do chinh xac cua mo hinh:", accuracy_score(y_test, y_pred))

[[ 7420     4     2     3     1     0     0     0     1     2     1     1]
 [ 8960     4     4     4     1     0     0     0     1     3     0     1]
 [ 9960     3     2     2     1     0     1     0     0     2     1     2]
 [ 7500     4     2     2     1     0     1     0     1     3     1     1]
 [ 7420     4     1     2     1     1     1     0     1     2     0     1]
 [ 7500     3     3     1     1     0     1     0     1     2     1     2]
 [ 8580     4     3     4     1     0     0     0     1     2     1     2]
 [16200     5     3     2     1     0     0     0     0     0     0     0]
 [ 8100     4     1     2     1     1     1     0     1     2     1     1]
 [ 5750     3     2     4     1     1     0     0     1     1     1     0]
 [13200     3     1     2     1     0     1     0     1     2     1     1]
 [ 6000     4     3     2     1     1     1     1     0     2     0     2]
 [ 6550     4     2     2     1     0     0     0     1     1     1     2]
 [ 3500     4     2     2

In [ ]:
Housing.replace({'yes': 1, 'no': 0, 'furnished': 1, 'unfurnished': 0, 'semi-furnished': 2}, inplace=True)
X = Housing.drop('price', axis=1).values
print(X[:20])

y = Housing['price'].values
print(y[:20])

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
sc = StandardScaler()
sc.fit(x_test)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

model = Perceptron(max_iter = 1000000000, eta0= 0.2, random_state = 0) #so lan train, toc do hoc
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)

print(y_pred[:20])
print(y_test[:20].T)
print("Do chinh xac cua mo hinh:", accuracy_score(y_test, y_pred))

[[ 7420     4     2     3     1     0     0     0     1     2     1     1]
 [ 8960     4     4     4     1     0     0     0     1     3     0     1]
 [ 9960     3     2     2     1     0     1     0     0     2     1     2]
 [ 7500     4     2     2     1     0     1     0     1     3     1     1]
 [ 7420     4     1     2     1     1     1     0     1     2     0     1]
 [ 7500     3     3     1     1     0     1     0     1     2     1     2]
 [ 8580     4     3     4     1     0     0     0     1     2     1     2]
 [16200     5     3     2     1     0     0     0     0     0     0     0]
 [ 8100     4     1     2     1     1     1     0     1     2     1     1]
 [ 5750     3     2     4     1     1     0     0     1     1     1     0]
 [13200     3     1     2     1     0     1     0     1     2     1     1]
 [ 6000     4     3     2     1     1     1     1     0     2     0     2]
 [ 6550     4     2     2     1     0     0     0     1     1     1     2]
 [ 3500     4     2     2